'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import QRCode from 'qrcode';
import { ShieldCheck, ShieldAlert, Loader2, Lock } from 'lucide-react';
import styles from './mfa.module.css';

export default function MFAPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [verifying, setVerifying] = useState(false);
  const [needsSetup, setNeedsSetup] = useState(false);
  const [qrDataUrl, setQrDataUrl] = useState('');
  const [token, setToken] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    // Check if the user already has verified setup in their cookies
    fetch('/api/mfa/status')
      .then(res => res.json())
      .then(data => {
        if (data.hasVerifiedSetup) {
          setNeedsSetup(false);
          setLoading(false);
        } else {
          // Generate new secret for first time setup
          fetch('/api/mfa/generate', { method: 'POST' })
            .then(res => res.json())
            .then(async (genData) => {
              try {
                const url = await QRCode.toDataURL(genData.otpauth);
                setQrDataUrl(url);
              } catch (err) {
                console.error('Error generating QR code', err);
              }
              setNeedsSetup(true);
              setLoading(false);
            });
        }
      })
      .catch(err => {
        console.error(err);
        setError('Failed to initialize MFA.');
        setLoading(false);
      });
  }, []);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (token.length !== 6) {
      setError('Please enter a valid 6-digit code.');
      return;
    }

    setVerifying(true);
    setError('');

    try {
      const res = await fetch('/api/mfa/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token }),
      });

      const data = await res.json();

      if (res.ok && data.success) {
        // MFA successful, redirect to consent page
        router.push('/consent');
      } else {
        setError(data.error || 'Invalid code. Please try again.');
        setVerifying(false);
      }
    } catch {
      setError('A network error occurred. Please try again.');
      setVerifying(false);
    }
  };

  if (loading) {
    return (
      <div className={styles.container}>
        <Loader2 className="animate-spin" size={48} color="var(--primary)" />
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <ShieldCheck size={48} color="var(--primary)" style={{ margin: '0 auto 1.5rem' }} />
        <h1 className={styles.title}>Two-Factor Authentication</h1>
        <p className={styles.subtitle}>
          Secure your account using an authenticator app (e.g. Google Authenticator, Authy, or Microsoft Authenticator).
        </p>

        {needsSetup && (
          <>
            <p style={{ color: 'var(--text-main)', marginBottom: '1rem', fontWeight: 500 }}>
              1. Scan this QR code with your authenticator app
            </p>
            {qrDataUrl && (
              <div className={styles.qrContainer}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={qrDataUrl} alt="MFA QR Code" className={styles.qrImage} width={200} height={200} />
              </div>
            )}
            <p style={{ color: 'var(--text-main)', marginBottom: '2rem', fontWeight: 500 }}>
              2. Enter the 6-digit code generated by the app
            </p>
          </>
        )}

        {!needsSetup && (
          <p style={{ color: 'var(--text-main)', marginBottom: '2rem', fontWeight: 500 }}>
            Enter the 6-digit code from your authenticator app
          </p>
        )}

        <form onSubmit={handleVerify}>
          <div className={styles.inputGroup}>
            <label className={styles.label} htmlFor="token">Authentication Code</label>
            <input
              id="token"
              type="text"
              inputMode="numeric"
              pattern="[0-9]*"
              maxLength={6}
              className={styles.input}
              placeholder="000000"
              value={token}
              onChange={(e) => setToken(e.target.value.replace(/\D/g, ''))}
              autoComplete="one-time-code"
              required
            />
          </div>

          {error && <div className={styles.error}>{error}</div>}

          <button type="submit" className={styles.button} disabled={verifying || token.length !== 6}>
            {verifying ? (
              <><Loader2 className="animate-spin" size={20} /> Verifying...</>
            ) : (
              <><Lock size={20} /> Verify & Continue</>
            )}
          </button>
        </form>

        <div className={styles.warningBox}>
          <ShieldAlert size={20} style={{ flexShrink: 0, marginTop: '2px' }} />
          <span>
            <strong>Zero-Trust Architecture:</strong> This step is required for all clinical personnel to comply with our Enterprise BAA. Do not share your 6-digit codes.
          </span>
        </div>
      </div>
    </div>
  );
}
